"""initial

Revision ID: 4ae2e205f9b7
Revises: 
Create Date: 2026-04-19 15:16:48.269999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ae2e205f9b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('mca_status', sa.String(length=30), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin')
    )
    op.create_index('idx_entities_cin', 'entities', ['cin'], unique=False, postgresql_where='cin IS NOT NULL')
    op.create_index('idx_entities_name_trgm', 'entities', ['entity_name'], unique=False, postgresql_using='gin', postgresql_ops={'entity_name': 'gin_trgm_ops'})
    op.create_index('idx_entities_type', 'entities', ['entity_type'], unique=False)
    op.create_table('mca_company_master',
    sa.Column('cin', sa.String(length=21), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('company_status', sa.String(length=30), nullable=True),
    sa.Column('company_class', sa.String(length=30), nullable=True),
    sa.Column('date_of_incorporation', sa.Date(), nullable=True),
    sa.Column('registered_state', sa.String(length=50), nullable=True),
    sa.Column('roc', sa.String(length=50), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('cin')
    )
    op.create_index('idx_mca_name_trgm', 'mca_company_master', ['company_name'], unique=False, postgresql_using='gin', postgresql_ops={'company_name': 'gin_trgm_ops'})
    op.create_index('idx_mca_status', 'mca_company_master', ['company_status'], unique=False)
    op.create_table('regulators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('violation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'subtype')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('regulator_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('raw_storage_key', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['regulator_id'], ['regulators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('idx_documents_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('idx_documents_regulator', 'documents', ['regulator_id'], unique=False)
    op.create_index('idx_documents_scraped', 'documents', ['scraped_at'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['processing_status'], unique=False)
    op.create_table('entity_resolution_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracted_name', sa.Text(), nullable=False),
    sa.Column('resolved_entity_id', sa.Integer(), nullable=True),
    sa.Column('resolution_method', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resolved_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulator_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('documents_found', sa.Integer(), nullable=True),
    sa.Column('documents_new', sa.Integer(), nullable=True),
    sa.Column('documents_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['regulator_id'], ['regulators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('regulator_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('violation_type_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('violation_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('violation_category', sa.String(length=50), nullable=True),
    sa.Column('violation_subtype', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('appeal_status', sa.String(length=30), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['regulator_id'], ['regulators.id'], ),
    sa.ForeignKeyConstraint(['violation_type_id'], ['violation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_violations_entity', 'violations', ['entity_id'], unique=False)
    op.create_index('idx_violations_order_date', 'violations', ['order_date'], unique=False)
    op.create_index('idx_violations_regulator', 'violations', ['regulator_id'], unique=False)
    op.create_index('idx_violations_review', 'violations', ['review_status'], unique=False, postgresql_where="review_status = 'pending_review'")
    op.create_index('idx_violations_type', 'violations', ['violation_category', 'violation_subtype'], unique=False)
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('penalty_type', sa.String(length=30), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_raw_text', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_penalties_amount', 'penalties', ['amount_inr'], unique=False, postgresql_where='amount_inr IS NOT NULL')
    op.create_index('idx_penalties_violation', 'penalties', ['violation_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_queue_status', 'review_queue', ['status', 'priority'], unique=False)
    op.create_table('violation_entities',
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('violation_id', 'entity_id', 'role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_entities')
    op.drop_index('idx_review_queue_status', table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index('idx_penalties_violation', table_name='penalties')
    op.drop_index('idx_penalties_amount', table_name='penalties', postgresql_where='amount_inr IS NOT NULL')
    op.drop_table('penalties')
    op.drop_index('idx_violations_type', table_name='violations')
    op.drop_index('idx_violations_review', table_name='violations', postgresql_where="review_status = 'pending_review'")
    op.drop_index('idx_violations_regulator', table_name='violations')
    op.drop_index('idx_violations_order_date', table_name='violations')
    op.drop_index('idx_violations_entity', table_name='violations')
    op.drop_table('violations')
    op.drop_table('scrape_runs')
    op.drop_table('entity_resolution_log')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_scraped', table_name='documents')
    op.drop_index('idx_documents_regulator', table_name='documents')
    op.drop_index('idx_documents_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_table('violation_types')
    op.drop_table('regulators')
    op.drop_index('idx_mca_status', table_name='mca_company_master')
    op.drop_index('idx_mca_name_trgm', table_name='mca_company_master', postgresql_using='gin', postgresql_ops={'company_name': 'gin_trgm_ops'})
    op.drop_table('mca_company_master')
    op.drop_index('idx_entities_type', table_name='entities')
    op.drop_index('idx_entities_name_trgm', table_name='entities', postgresql_using='gin', postgresql_ops={'entity_name': 'gin_trgm_ops'})
    op.drop_index('idx_entities_cin', table_name='entities', postgresql_where='cin IS NOT NULL')
    op.drop_table('entities')
    # ### end Alembic commands ###
